### ISSUE TITLE
Incorrect suffix for s390x linux license

### ISSUE THREAD

**Issue by prankkelkar** [teamserverless/license-check#13]
## Expected Behaviour

After running https://raw.githubusercontent.com/teamserverless/license-check/master/get.sh on s390x platform it should download the licence.

## Current Behaviour
Getting error:
```root@ropey1:~/prasanna# curl -fsSL $url > license-check
curl: (22) The requested URL returned error: 404 Not Found
```

## Possible Solution

Change suffix from "s390x" to "-s390x" and it works fine.

## Steps to Reproduce (for bugs)

Run the above script with arch=s390x

## Context

Licence check fails for s390x.

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux s390x

**Comment by prankkelkar** [comment]
@alexellis Please fix this typo. I am working on openfaas and almost all dockerfiles use this licence and because of this error i am facing difficulties in building dockerfiles.

**Comment by alexellis** [comment]
We don't seem to be getting this issue at all with the regular builds.

If you want to provide your own PR I'd be happy to review it.

**Comment by alexellis** [comment]
Fixed in https://github.com/teamserverless/license-check/releases/tag/0.3.4

**Comment by prankkelkar** [comment]
Thanks for the fix.
