### ISSUE TITLE
[Proposal] Publish a docker image

### ISSUE THREAD

**Issue by LucasRoesler** [teamserverless/license-check#14]
Currently, we need to install and user license-check via curl and piping to sh

```sh
curl https://raw.githubusercontent.com/teamserverless/license-check/master/get.sh | sh
```

for example here, https://github.com/openfaas/faas-netes/blob/0fe88f3a672c45335e644854f44811a1db287d69/Dockerfile#L6-L7

## Expected Behaviour

In a dockerfile I would prefer to use

```docker
COPY  --from=teamserverless/license-check:v1.0 /usr/bin/license-check /usr/bin/license-check
```

This would allow for better layer caching and, I think, simplify Dockerfiles. It would even allow very simple versioning in dockerfile or for someone to run the license-check via `docker run`.  

## Context

I was thinking about this while update the `faas-cli` project

**Comment by alexellis** [comment]
Very supportive of this. The watchdog publishes it's image in this way, if anyone would like to spend an hour or so on porting the logic across to here?
