### ISSUE TITLE
Add s390x and ppc64le support

### ISSUE THREAD

**Issue by imdurgadas** [teamserverless/license-check#7]
License check is wonderful utility that could be used by various teams and integrate in their pipeline. Being opensource, it would be great if we can extend it to powerful architectures like zOS which is being widely used for machine learning / AI development.
We are also planning to build openfaas for various platforms and license check is failing as it doesn't support the same.

**Comment by alexellis** [comment]
Hi,

Thank you for writing up why you need this, it helps.

Which platforms do you have a specific need for at your company?

Alex

**Comment by imdurgadas** [comment]
zOS for now.

**Comment by alexellis** [comment]
Shall we just add zOS only then in your PR?

**Comment by imdurgadas** [comment]
Sure. I will update the PR then.

**Comment by alexellis** [comment]
@imdurgadas see also: #9 which adds ppc64le

**Comment by alexellis** [comment]
Derek close: both platforms are now available.
